version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: fluxsight-postgres
    environment:
      POSTGRES_DB: fluxsight
      POSTGRES_USER: fluxsight
      POSTGRES_PASSWORD: fluxsight_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_preload_libraries=timescaledb
      -c timescaledb.telemetry_level=off
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  redis:
    image: redis:7-alpine
    container_name: fluxsight-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  fluxsight-api:
    build: .
    container_name: fluxsight-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://fluxsight:fluxsight_password@postgres:5432/fluxsight
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./keys:/app/keys:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
