version: '3.8'

services:
  analytics-app:
    build: .
    ports:
      - "42069:42069"
    environment:
      - NODE_ENV=production
      - PORT=42069
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/analytics
      - DATABASE_SCHEMA=public
      - PONDER_RPC_URL_1=${PONDER_RPC_URL_1}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
